### PR TITLE
We need a "report issue" button

### PR DESCRIPTION
**Pull request by bnchdrff**

### CODE REVIEW

**Comment by bnchdrff** [comment]
how's [this](https://github.com/detroitledger/gnl_profile/compare/77-flagging?expand=1#diff-2625016b50d68d922257f74801cac29cR259) look?

**Comment by bnchdrff** [comment]
also i'll set up an RSS feed of recent flags + a view to see flags on the backend

**Comment by bnchdrff** [comment]
rss feed done! create API done!

**Comment by bnchdrff** [comment]
converted to PR using http://issue2pr.herokuapp.com/ (cool)

**Comment by hampelm** [comment]
Very cool! No auth needed to create notes? If so, good to merge!

**Comment by bnchdrff** [comment]
tested on a staging site + pulled changes into live!

**Pull request merged**
